baseURL = "https://eclectic-sfogliatella-572e20.netlify.app/"
languageCode = "en-us"
title = "My Portfolio"
theme = "hugo-profile"

#Enable syntax highlighting
pygmentsCodeFences = true
pymentsUseClasses = true
