[build]
publish = "/opt/build/repo/public"
command = "hugo --gc --minify"
publishOrigin= "config"
commandOrigin= "config"

[context.production.environment]
HUGO_VERSION = "0.143.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"




